apiVersion: v1
kind: ConfigMap
metadata:
  name: tcb-trino-coordinator
  labels:
    app: trino
    chart: trino-0.2.0
    release: tcb
    heritage: Helm
    component: coordinator
data:
  node.properties: |
    node.environment=production
    node.data-dir=/data/trino
    plugin.dir=/usr/lib/trino/plugin

  jvm.config: |
    -server
    -Xmx8G
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+UseGCOverheadLimit
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
    -Djdk.attach.allowAttachSelf=true
    -XX:-UseBiasedLocking
    -XX:ReservedCodeCacheSize=512M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.nio.maxCachedBufferSize=2000000

  config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=true

    query.max-memory=4GB
    query.max-memory-per-node=1GB
    memory.heap-headroom-per-node=1GB

    discovery-server.enabled=true

    #http-server.http.enabled=true
    #http-server.http.port=8080

    http-server.http.enabled=false
    node.internal-address=tcb-trino-coordinator-0.trino-headless.trino.svc.cluster.local
    http-server.https.enabled=true
    http-server.https.port=8443
    http-server.https.keystore.path=/etc/trino/certs/trino-keystore.jks
    http-server.https.keystore.key=bassim    
    discovery.uri=https://tcb-trino-coordinator-0.trino-headless.trino.svc.cluster.local:8443


    internal-communication.https.required=true
    internal-communication.https.keystore.path=/etc/trino/certs/trino-keystore.jks
    internal-communication.https.keystore.key=bassim
    internal-communication.shared-secret=9R5bUGPMyV8FA4pXtIC79BEo4FsARE0YVv02eNVoStPn+pH1cGh8uCvyednGV+0DdqC7OanQ70j8K2wSfbVOYRIVh2GpqTIk6YMSVZMT056o0ligt6CQmr1XPXV1vOB8ZIqbvrEnNScqQgGiBSU1HUjafoqVHylliKZsKqSjkghf1ufdNO4WKP8G3SocwJ06Gk/e82mpFhPl817xHE4IQIe13Q6RwPJVLrGgyODPgb9I6hbFZHAAmJes5UJfBIALhzcrxRJk4qUbM/pWuSK+xG6zjgoUrAaUnAnktjVXXrPt278Wo4itfPF19ZDmtu8jSiJBE114+krIbdgEKMXT2e5zYZIOOyqbrh3k4kOIpkaKPfjXpLrQLmI5h48zZj03zcmV5AoYOxE6MyKlERHd61pZCYTOHJY+zIrYDWhmf33yz7iZPxx8TqCDhie1VfXnRlqT4R3FaloeOs5erP5BkGjEmsVVhCNoW70aBmRzL82fDdDmN8ZmETz+a43X300/9KiYGojyvGX7YtPqdB/0tYpeFQUXeonz0xZA7fWmNvfP8QwuAsg4tCpbz15eKRbhpMp/QlBAO5vciww8Yy4YIJw42koQX173oljR2pn/fhjXQPndO111VuJaYf07jOW/69Eix90NKlrNq7tjhlUDZKc58n0Afn6ttNKtpXZfpa4=
    
    http-server.authentication.type=PASSWORD
    

  log.properties: |
    io.trino=INFO
  
  password.db: |
    test:$2y$10$5rhqMAQkfe5qbMBPb2pHyOiSory6b3PbBV5Zp7bHbfSS3bII/5eHG

  password-authenticator.properties: |
    password-authenticator.name=file
    file.password-file=/etc/trino/password.db